apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-selector
spec:
  replicas: 3
  selector:
    matchLabels:
      name: node-sel
  template:
    metadata:
      labels:
        name: node-sel
    spec:
      containers:
      - name: nginx
        image: nginx:1.13.9-alpine
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 128Mi
            cpu: 250m
#      nodeSelector:
#        disktype: ssd